spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/music-service
    username: postgres
    password: 1
  jpa:
    show-sql: true
server:
  error:
    include-message: always
token: 6926246907:AAGCQ-CkORgbPMdEqn0PrkSzdrAFZqsIEmo
